"""
Connolly surface calculation for molecular visualization.

A Connolly surface (also known as molecular surface or solvent-accessible surface)
is generated by rolling a probe sphere over the van der Waals surface of atoms.
"""

import math
from typing import Tuple

import numpy as np
from decologr import Decologr as log
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import laplacian
from scipy.spatial.distance import cdist
from skimage import measure  # skimage.measure.marching_cubes

# Global cache for Connolly surface calculations to prevent race conditions
_connolly_surface_cache = {}
_cache_hits = 0
_cache_misses = 0


def _get_cache_key(
    atom_positions, atom_radii, probe_radius, grid_spacing, density, padding, smoothing
):
    """Generate a cache key for Connolly surface parameters."""
    import hashlib

    ap = np.asarray(atom_positions)
    ar = np.asarray(atom_radii)
    # Create a hash of the parameters that affect the surface calculation
    key_data = {
        "atom_positions": ap.tobytes() if ap.size > 0 else b"",
        "atom_radii": ar.tobytes() if ar.size > 0 else b"",
        "probe_radius": probe_radius,
        "grid_spacing": grid_spacing,
        "density": density,
        "padding": padding,
        "smoothing": smoothing,
    }

    # Create a hash of the key data using hashlib for better performance
    key_string = str(sorted(key_data.items()))
    return hashlib.md5(key_string.encode()).hexdigest()


def _get_cached_connolly_surface(
    atom_positions, atom_radii, probe_radius, grid_spacing, density, padding, smoothing
):
    """Get cached Connolly surface if available."""
    global _cache_hits, _cache_misses

    cache_key = _get_cache_key(
        atom_positions,
        atom_radii,
        probe_radius,
        grid_spacing,
        density,
        padding,
        smoothing,
    )

    if cache_key in _connolly_surface_cache:
        _cache_hits += 1
        log.debug(
            f"Connolly surface cache HIT ({_cache_hits} hits, {_cache_misses} misses)"
        )
        return _connolly_surface_cache[cache_key]

    _cache_misses += 1
    log.debug(
        f"Connolly surface cache MISS ({_cache_hits} hits, {_cache_misses} misses)"
    )
    return None


def _cache_connolly_surface(
    atom_positions,
    atom_radii,
    probe_radius,
    grid_spacing,
    density,
    padding,
    smoothing,
    result,
):
    """Cache Connolly surface result."""
    try:
        cache_key = _get_cache_key(
            atom_positions,
            atom_radii,
            probe_radius,
            grid_spacing,
            density,
            padding,
            smoothing,
        )
        _connolly_surface_cache[cache_key] = result

        # Limit cache size to prevent memory issues
        if len(_connolly_surface_cache) > 5:  # Reduced cache size
            # Remove oldest entries (simple FIFO)
            oldest_key = next(iter(_connolly_surface_cache))
            del _connolly_surface_cache[oldest_key]
    except Exception as e:
        log.warning(f"⚠️ Failed to cache Connolly surface result: {e}")
        # Don't let caching errors break the main functionality


def clear_connolly_surface_cache():
    """Clear the Connolly surface cache."""
    global _connolly_surface_cache, _cache_hits, _cache_misses
    _connolly_surface_cache.clear()
    _cache_hits = 0
    _cache_misses = 0
    log.info("🧹 Connolly surface cache cleared")


def smooth_surface(
    vertices: np.ndarray, faces: np.ndarray, iterations: int = 1
) -> np.ndarray:
    """Apply Laplacian smoothing to surface vertices for better quality."""
    if len(vertices) == 0 or len(faces) == 0:
        return vertices

    smoothed_vertices = vertices.copy()

    for _ in range(iterations):
        # Build adjacency matrix
        n_vertices = len(vertices)
        adj_matrix = np.zeros((n_vertices, n_vertices), dtype=bool)

        # For each face, mark adjacent vertices
        for face in faces:
            i, j, k = face
            adj_matrix[i, j] = adj_matrix[j, i] = True
            adj_matrix[i, k] = adj_matrix[k, i] = True
            adj_matrix[j, k] = adj_matrix[k, j] = True

        # Apply Laplacian smoothing
        for i in range(n_vertices):
            neighbors = np.where(adj_matrix[i])[0]
            if len(neighbors) > 0:
                smoothed_vertices[i] = np.mean(vertices[neighbors], axis=0)

    return smoothed_vertices


def calculate_connolly_surface(
    atom_positions: np.ndarray,
    atom_radii: np.ndarray,
    probe_radius: float = 1.4,
    grid_spacing: float = 0.5,
    density: float = 1.0,
    padding: float = 5.0,
    smoothing: bool = True,
    progress_callback=None,
    use_global_cache: bool = True,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Calculate Connolly surface using a signed distance field + marching cubes."""

    try:
        # Check cache first to prevent race conditions (only if enabled)
        if use_global_cache:
            cached_result = _get_cached_connolly_surface(
                atom_positions,
                atom_radii,
                probe_radius,
                grid_spacing,
                density,
                padding,
                smoothing,
            )
            if cached_result is not None:
                return cached_result
    except Exception as e:
        log.warning(f"⚠️ Cache lookup failed, proceeding with calculation: {e}")
        # Continue with calculation even if cache fails

    try:
        # Parameter validation
        if atom_positions.size == 0:
            log.debug("Empty atom positions, returning empty surface")
            return np.array([]), np.array([]), np.array([])

        if len(atom_positions) != len(atom_radii):
            log.warning(
                f"Mismatch between atom positions ({len(atom_positions)}) and radii ({len(atom_radii)})"
            )
            return np.array([]), np.array([]), np.array([])

        if probe_radius <= 0:
            log.warning(f"Invalid probe radius: {probe_radius}, using default 1.4")
            probe_radius = 1.4

        if grid_spacing <= 0:
            log.warning(f"Invalid grid spacing: {grid_spacing}, using default 0.5")
            grid_spacing = 0.5

        log.debug(
            f"Connolly surface calculation starting with {len(atom_positions)} atoms"
        )

        # Calculate bounding box
        min_coords = np.min(atom_positions - atom_radii[:, None] - probe_radius, axis=0)
        max_coords = np.max(atom_positions + atom_radii[:, None] + probe_radius, axis=0)
        min_coords -= padding
        max_coords += padding

        # Adjust grid spacing based on molecule size to prevent overly large meshes
        molecule_size = np.max(max_coords - min_coords)
        estimated_vertices = (molecule_size / grid_spacing) ** 3

        # If estimated mesh would be too large, increase grid spacing
        if estimated_vertices > 2_000_000:  # Conservative estimate
            original_grid_spacing = grid_spacing
            grid_spacing = max(
                grid_spacing, molecule_size / 100
            )  # Ensure reasonable resolution
            log.info(
                f"🔧 Adjusting grid spacing from {original_grid_spacing:.3f} to {grid_spacing:.3f} to prevent large mesh"
            )

        # Create grid
        eps = 1e-9
        xs = np.arange(
            min_coords[0], max_coords[0] + eps, grid_spacing, dtype=np.float32
        )
        ys = np.arange(
            min_coords[1], max_coords[1] + eps, grid_spacing, dtype=np.float32
        )
        zs = np.arange(
            min_coords[2], max_coords[2] + eps, grid_spacing, dtype=np.float32
        )

        nx, ny, nz = len(xs), len(ys), len(zs)
        log.info(f"🔬 Grid size: {nx} x {ny} x {nz} -> total {nx * ny * nz:,} points")

        if progress_callback:
            progress_callback(10, 100, "Setting up grid...")

        # Initialize distance field
        distance_field = np.full((nx, ny, nz), np.inf, dtype=np.float32)
        grid_origin = min_coords.copy()

        # Process each atom
        n_atoms = atom_positions.shape[0]
        if progress_callback:
            progress_callback(20, 100, "Processing atoms...")

        for atom_idx in range(n_atoms):
            if progress_callback and atom_idx % 100 == 0:
                progress_callback(
                    20 + int(60 * atom_idx / n_atoms),
                    100,
                    f"Processed {atom_idx}/{n_atoms} atoms",
                )

            atom_pos = atom_positions[atom_idx]
            atom_radius = atom_radii[atom_idx]

            # Calculate bounding box for this atom
            atom_min = atom_pos - atom_radius - probe_radius
            atom_max = atom_pos + atom_radius + probe_radius

            # Convert to grid indices
            i_min = max(0, int((atom_min[0] - grid_origin[0]) / grid_spacing))
            i_max = min(nx - 1, int((atom_max[0] - grid_origin[0]) / grid_spacing))
            j_min = max(0, int((atom_min[1] - grid_origin[1]) / grid_spacing))
            j_max = min(ny - 1, int((atom_max[1] - grid_origin[1]) / grid_spacing))
            k_min = max(0, int((atom_min[2] - grid_origin[2]) / grid_spacing))
            k_max = min(nz - 1, int((atom_max[2] - grid_origin[2]) / grid_spacing))

            if i_min > i_max or j_min > j_max or k_min > k_max:
                continue

            # Create local grid
            local_xs = xs[i_min : i_max + 1]
            local_ys = ys[j_min : j_max + 1]
            local_zs = zs[k_min : k_max + 1]

            if len(local_xs) == 0 or len(local_ys) == 0 or len(local_zs) == 0:
                continue

            # Create 3D grid for this atom
            X, Y, Z = np.meshgrid(local_xs, local_ys, local_zs, indexing="ij")
            grid_points = np.stack([X.ravel(), Y.ravel(), Z.ravel()], axis=1)

            # Calculate distances
            distances = np.linalg.norm(grid_points - atom_pos, axis=1)
            # For Connolly surface, the surface is at atom_radius + probe_radius from the center
            local_distances = (distances - atom_radius - probe_radius).reshape(X.shape)

            # Update distance field
            distance_field[i_min : i_max + 1, j_min : j_max + 1, k_min : k_max + 1] = (
                np.minimum(
                    distance_field[
                        i_min : i_max + 1, j_min : j_max + 1, k_min : k_max + 1
                    ],
                    local_distances,
                )
            )

        if progress_callback:
            progress_callback(80, 100, "Extracting isosurface...")

        # Extract isosurface
        try:
            result = measure.marching_cubes(
                distance_field,
                level=0,
                spacing=(grid_spacing, grid_spacing, grid_spacing),
            )
            if len(result) == 4:
                vertices, faces, normals, _ = result
            else:
                vertices, faces, normals = result

            # Transform vertices back to world coordinates
            vertices += grid_origin

            # Check mesh size and decimate if too large
            max_vertices = 5_000_000  # Half the renderer limit for safety
            max_faces = 5_000_000

            if len(vertices) > max_vertices or len(faces) > max_faces:
                log.warning(
                    f"⚠️ Connolly surface too large ({len(vertices)} vertices, {len(faces)} faces), decimating..."
                )

                # Simple decimation: keep every nth vertex/face
                vertex_ratio = max_vertices / len(vertices)
                face_ratio = max_faces / len(faces)
                decimation_ratio = min(vertex_ratio, face_ratio, 1.0)

                if decimation_ratio < 1.0:
                    # Decimate vertices
                    n_keep_vertices = int(len(vertices) * decimation_ratio)
                    vertex_indices = np.linspace(
                        0, len(vertices) - 1, n_keep_vertices, dtype=int
                    )
                    vertices = vertices[vertex_indices]

                    # Decimate faces (keep only faces that reference kept vertices)
                    max_vertex_idx = len(vertices) - 1
                    valid_faces = np.all(faces <= max_vertex_idx, axis=1)
                    faces = faces[valid_faces]

                    # Reindex faces to match new vertex indices
                    vertex_map = {
                        old_idx: new_idx
                        for new_idx, old_idx in enumerate(vertex_indices)
                    }
                    faces = np.array(
                        [
                            [
                                vertex_map[face[0]],
                                vertex_map[face[1]],
                                vertex_map[face[2]],
                            ]
                            for face in faces
                            if all(v in vertex_map for v in face)
                        ]
                    )

                    # Decimate normals if they exist
                    if len(normals) > 0:
                        normals = normals[vertex_indices]

                    log.info(
                        f"🔧 Decimated to {len(vertices)} vertices, {len(faces)} faces"
                    )

            # Apply smoothing if requested (only if mesh is not too large)
            if smoothing and len(vertices) < 1_000_000:  # Only smooth smaller meshes
                vertices = smooth_surface(vertices, faces, iterations=1)

            if progress_callback:
                progress_callback(100, 100, "Connolly surface complete")

            log.info(
                f"✅ Connolly surface generated: {len(vertices)} vertices, {len(faces)} faces"
            )

            # Cache the result (with error handling) - only if global cache is enabled
            if use_global_cache:
                try:
                    _cache_connolly_surface(
                        atom_positions,
                        atom_radii,
                        probe_radius,
                        grid_spacing,
                        density,
                        padding,
                        smoothing,
                        (vertices, faces, normals),
                    )
                except Exception as e:
                    log.warning(f"⚠️ Failed to cache result: {e}")
                    # Continue anyway - caching is not critical

            return vertices, faces, normals

        except Exception as e:
            log.error(f"❌ Error in marching cubes: {e}")
            return np.array([]), np.array([]), np.array([])

    except Exception as ex:
        log.error(f"❌ Error calculating Connolly surface: {ex}")
        return np.array([]), np.array([]), np.array([])


def calculate_connolly_surface_from_molecule(
    molecule,
    probe_radius: float = 1.4,
    grid_spacing: float = 0.5,
    density: float = 1.0,
    padding: float = 5.0,
    smoothing: bool = True,
    progress_callback=None,
    use_global_cache: bool = True,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Calculate Connolly surface from a molecule object."""
    try:
        # Collect all atom positions and elements
        atom_positions = []
        elements = []

        for model in molecule.models:
            for chain in model.chains.values():
                for residue in chain.residues:
                    for atom in residue.atoms.values():
                        atom_positions.append(atom.pos)
                        elements.append(atom.element)

        if not atom_positions:
            log.warning("⚠️ No atoms found in molecule")
            return np.array([]), np.array([]), np.array([])

        atom_positions = np.array(atom_positions)
        atom_radii = get_atom_radii_from_elements(elements)

        log.info(f"🔬 Found {len(atom_positions)} atoms")

        return calculate_connolly_surface(
            atom_positions,
            atom_radii,
            probe_radius,
            grid_spacing,
            density,
            padding,
            smoothing,
            progress_callback,
            use_global_cache=use_global_cache,
        )

    except Exception as ex:
        log.error(f"❌ Error calculating Connolly surface from molecule: {ex}")
        return np.array([]), np.array([]), np.array([])


def get_atom_radii_from_elements(elements):
    """Get van der Waals radii for elements."""
    # Van der Waals radii in Angstroms
    vdw_radii = {
        "H": 1.20,
        "C": 1.70,
        "N": 1.55,
        "O": 1.52,
        "F": 1.47,
        "P": 1.80,
        "S": 1.80,
        "Cl": 1.75,
        "Br": 1.85,
        "I": 1.98,
        "Na": 2.27,
        "Mg": 1.73,
        "Ca": 2.31,
        "Zn": 1.39,
        "Fe": 2.00,
    }

    radii = []
    for element in elements:
        radii.append(vdw_radii.get(element, 1.5))  # Default radius for unknown elements

    return np.array(radii)


# Global cache for spatial indices to avoid rebuilding
_spatial_index_cache = {}


def _get_cached_spatial_index(atom_positions: np.ndarray, atom_colors: np.ndarray):
    """Get or create a cached spatial index for atom positions."""
    # Create a hash of the atom positions
    positions_hash = hash(atom_positions.tobytes())

    if positions_hash in _spatial_index_cache:
        return _spatial_index_cache[positions_hash]

    # Create spatial index
    from scipy.spatial import cKDTree

    atom_tree = cKDTree(atom_positions)
    _spatial_index_cache[positions_hash] = (atom_tree, atom_colors)

    return atom_tree, atom_colors


def create_connolly_surface_colors(vertices: np.ndarray, *args, **kwargs) -> np.ndarray:
    """Create colors for Connolly surface vertices based on nearest atoms.

    Supports multiple calling patterns:
    1. create_connolly_surface_colors(vertices, "uniform") - uniform coloring
    2. create_connolly_surface_colors(vertices, "atom", atom_positions, atom_colors) - atom-based coloring
    3. create_connolly_surface_colors(vertices, atom_positions, atom_colors, uniform_color=None) - direct atom coloring
    """
    if len(vertices) == 0:
        return np.array([])

    # Handle different calling patterns
    if len(args) == 0:
        # No arguments - use uniform color
        uniform_color = kwargs.get("uniform_color", (0.2, 0.6, 1.0))
        return np.tile(uniform_color, (len(vertices), 1))

    if len(args) == 1 and isinstance(args[0], str):
        # Pattern: create_connolly_surface_colors(vertices, "uniform")
        if args[0] == "uniform":
            uniform_color = kwargs.get("uniform_color", (0.2, 0.6, 1.0))
            return np.tile(uniform_color, (len(vertices), 1))
        elif args[0] == "distance":
            # Distance-based coloring: green (low) to purple (high)
            distances = np.linalg.norm(vertices, axis=1)
            if len(distances) == 0:
                return np.array([])

            # Normalize distances to [0, 1]
            if np.max(distances) > np.min(distances):
                normalized_distances = (distances - np.min(distances)) / (
                    np.max(distances) - np.min(distances)
                )
            else:
                normalized_distances = np.zeros_like(distances)

            # Create color gradient: green (0) to purple (1)
            colors = np.zeros((len(vertices), 3))
            colors[:, 1] = 1.0 - normalized_distances  # Green component decreases
            colors[:, 2] = normalized_distances  # Blue component increases
            # Red component stays 0 for both green and purple

            return colors
        elif args[0] == "height":
            # Height-based coloring: blue (low) to red (high)
            heights = vertices[:, 2]  # Z-coordinate
            if len(heights) == 0:
                return np.array([])

            # Normalize heights to [0, 1]
            if np.max(heights) > np.min(heights):
                normalized_heights = (heights - np.min(heights)) / (
                    np.max(heights) - np.min(heights)
                )
            else:
                normalized_heights = np.zeros_like(heights)

            # Create color gradient: blue (0) to red (1)
            colors = np.zeros((len(vertices), 3))
            colors[:, 0] = normalized_heights  # Red component increases
            colors[:, 2] = 1.0 - normalized_heights  # Blue component decreases
            # Green component stays 0 for both blue and red

            return colors
        else:
            # Unknown string - fallback to uniform
            uniform_color = (0.2, 0.6, 1.0)
            return np.tile(uniform_color, (len(vertices), 1))

    if len(args) == 3 and isinstance(args[0], str) and args[0] == "atom":
        # Pattern: create_connolly_surface_colors(vertices, "atom", atom_positions, atom_colors)
        atom_positions = args[1]
        atom_colors = args[2]
        uniform_color = None  # No uniform color for atom-based coloring
    elif len(args) >= 2:
        # Pattern: create_connolly_surface_colors(vertices, atom_positions, atom_colors, uniform_color=None)
        atom_positions = args[0]
        atom_colors = args[1]
        uniform_color = kwargs.get("uniform_color", None)
    else:
        # Fallback to uniform color
        uniform_color = (0.2, 0.6, 1.0)
        return np.tile(uniform_color, (len(vertices), 1))

    # Check if we have valid atom data
    if atom_positions is None or len(atom_positions) == 0:
        uniform_color = (0.2, 0.6, 1.0)
        return np.tile(uniform_color, (len(vertices), 1))

    # If uniform color is specified, return that color for all vertices
    if uniform_color is not None:
        return np.tile(uniform_color, (len(vertices), 1))

    # Try to get cached spatial index
    atom_tree, cached_colors = _get_cached_spatial_index(atom_positions, atom_colors)

    if cached_colors is not None:
        # Use cached spatial index
        nearest_atom_indices = atom_tree.query(vertices)[1]

        # Get colors for nearest atoms
        colors = cached_colors[nearest_atom_indices]

        log.debug(
            f"Using cached spatial index: {len(vertices)} vertices, {len(atom_positions)} atoms"
        )
        # Log some sample colors for debugging
        if len(cached_colors) > 0:
            sample_indices = np.linspace(
                0, len(cached_colors) - 1, min(10, len(cached_colors)), dtype=int
            )
            log.debug(f"Sample atom colors: {cached_colors[sample_indices]}")

        # Log some statistics
        unique_atoms = np.unique(nearest_atom_indices)
        if len(unique_atoms) > 0 and len(atom_positions) > 0:
            # Ensure bincount array is large enough for all unique indices
            max_atom_idx = (
                np.max(nearest_atom_indices) if len(nearest_atom_indices) > 0 else 0
            )
            bincount = np.bincount(nearest_atom_indices, minlength=max_atom_idx + 1)
            most_selected_atom_idx = unique_atoms[np.argmax(bincount[unique_atoms])]
            if most_selected_atom_idx < len(
                atom_positions
            ) and most_selected_atom_idx < len(cached_colors):
                log.debug(
                    f"Most selected atom {most_selected_atom_idx}: position={atom_positions[most_selected_atom_idx]}, colour={cached_colors[most_selected_atom_idx]}"
                )
            else:
                log.debug(
                    f"Most selected atom index {most_selected_atom_idx} is out of bounds"
                )

        # Get unique colors in selected atoms
        selected_colors = cached_colors[nearest_atom_indices]
        unique_colors = np.unique(selected_colors, axis=0)
        log.debug(f"Unique colors in selected atoms: {len(unique_colors)}")
        log.debug(f"Selected colors: {unique_colors}")
        log.debug(
            f"Unique selected atom indices: {len(unique_atoms)} out of {len(atom_positions)} total atoms"
        )

        return colors

    # Fallback: create new spatial index
    from scipy.spatial import cKDTree

    atom_tree = cKDTree(atom_positions)
    nearest_atom_indices = atom_tree.query(vertices)[1]
    colors = atom_colors[nearest_atom_indices]

    return colors
